const Icons = {
  ic_dashboard: require("./ic_dashboard.svg").default,
  ic_edit: require("./ic_edit.svg").default,
  ic_hourglass_empty: require("./ic_hourglass_empty.svg").default,
  ic_group: require("./ic_group.svg").default,
  ic_logo: require("./ic_logo.svg").default,
  ic_more: require("./ic_more.svg").default,
  ic_image: require("./ic_image.svg").default,
  ic_linkedin: require("./ic_linkedin.svg").default,
  ic_facebook: require("./ic_facebook.svg").default,
  ic_twitter: require("./ic_twitter.svg").default,
  ic_instagram: require("./ic_instagram.svg").default,
  ic_usa: require("./ic_usa.svg").default,
  ic_nigeria: require("./ic_nigeria.svg").default,
  ic_netherlands: require("./ic_netherlands.svg").default,
  ic_andorra: require("./ic_andorra.svg").default,
  ic_delete: require("./ic_delete.svg").default,
  ic_photo: require("./ic_photo.svg").default,
  ic_subscription: require("./ic_subscription.svg").default,
  ic_alarm: require("./ic_alarm.svg").default,
  ic_file: require("./ic_file.svg").default,
  ic_info: require("./ic_info.svg").default,
};

export default Icons;
